import { DEFAULT_LOCALE, type Locale } from "./protocol.js";

export const desktopMenuMessageIds = {
  file: "titleBar.menu.file",
  edit: "titleBar.menu.edit",
  view: "titleBar.menu.view",
  window: "titleBar.menu.window",
  help: "titleBar.menu.help",
  fileNewTask: "titleBar.menu.file.newTask",
  fileOpenWorkspace: "titleBar.menu.file.openWorkspace",
  fileCloseWindow: "titleBar.menu.file.closeWindow",
  editUndo: "titleBar.menu.edit.undo",
  editRedo: "titleBar.menu.edit.redo",
  editCut: "titleBar.menu.edit.cut",
  editCopy: "titleBar.menu.edit.copy",
  editPaste: "titleBar.menu.edit.paste",
  editDelete: "titleBar.menu.edit.delete",
  editSelectAll: "titleBar.menu.edit.selectAll",
  viewToggleFullScreen: "titleBar.menu.view.toggleFullScreen",
  viewActualSize: "titleBar.menu.view.actualSize",
  viewZoomIn: "titleBar.menu.view.zoomIn",
  viewZoomOut: "titleBar.menu.view.zoomOut",
  windowMinimize: "titleBar.menu.window.minimize",
  windowZoom: "titleBar.menu.window.zoom",
  windowBringAllToFront: "titleBar.menu.window.bringAllToFront",
  appServices: "titleBar.menu.app.services",
  appHide: "titleBar.menu.app.hide",
  appHideOthers: "titleBar.menu.app.hideOthers",
  appShowAll: "titleBar.menu.app.showAll",
  appQuit: "titleBar.menu.app.quit",
  helpAbout: "titleBar.menu.help.about",
  helpWhatsNew: "titleBar.menu.help.whatsNew",
  helpCheckForUpdates: "titleBar.menu.help.checkForUpdates",
  helpToggleDevTools: "titleBar.menu.help.toggleDevTools",
  helpResourceManager: "titleBar.menu.help.resourceManager",
  helpToggleZCodeStdioTap: "titleBar.menu.help.toggleZCodeStdioTap",
  helpZCodeEndpoint: "titleBar.menu.help.zcodeEndpoint",
  helpZCodeEndpointProduction: "titleBar.menu.help.zcodeEndpoint.production",
  helpZCodeEndpointTest: "titleBar.menu.help.zcodeEndpoint.test",
  helpZCodeEndpointCustom: "titleBar.menu.help.zcodeEndpoint.custom",
  helpZCodeEndpointReset: "titleBar.menu.help.zcodeEndpoint.reset",
  helpFeedback: "titleBar.menu.help.feedback",
  helpExportLogs: "titleBar.menu.help.exportLogs",
  helpClearAllData: "titleBar.menu.help.clearAllData",
  helpCheckingForUpdates: "desktopMenu.help.checkingForUpdates",
  helpUpdateAvailableVersion: "desktopMenu.help.updateAvailableVersion",
  helpDownloadingUpdateVersion: "desktopMenu.help.downloadingUpdateVersion",
  helpDownloadingUpdateProgress: "desktopMenu.help.downloadingUpdateProgress",
  helpRestartToUpdate: "desktopMenu.help.restartToUpdate",
  dockShowCurrentWindow: "dock.menu.showCurrentWindow",
  trayTooltip: "tray.tooltip",
  trayOpenZCode: "tray.menu.openZCode",
  trayQuit: "tray.menu.quit",
} as const;

export type DesktopMenuMessageId =
  (typeof desktopMenuMessageIds)[keyof typeof desktopMenuMessageIds];

type DesktopMenuLocaleMessages = Record<DesktopMenuMessageId, string>;

export const desktopMenuMessages: Record<Locale, DesktopMenuLocaleMessages> = {
  "zh-CN": {
    "titleBar.menu.file": "文件",
    "titleBar.menu.edit": "编辑",
    "titleBar.menu.view": "视图",
    "titleBar.menu.window": "窗口",
    "titleBar.menu.help": "帮助",
    "titleBar.menu.file.newTask": "新建任务",
    "titleBar.menu.file.openWorkspace": "打开工作区",
    "titleBar.menu.file.closeWindow": "关闭窗口",
    "titleBar.menu.edit.undo": "撤销",
    "titleBar.menu.edit.redo": "重做",
    "titleBar.menu.edit.cut": "剪切",
    "titleBar.menu.edit.copy": "复制",
    "titleBar.menu.edit.paste": "粘贴",
    "titleBar.menu.edit.delete": "删除",
    "titleBar.menu.edit.selectAll": "全选",
    "titleBar.menu.view.toggleFullScreen": "切换全屏",
    "titleBar.menu.view.actualSize": "实际大小",
    "titleBar.menu.view.zoomIn": "放大",
    "titleBar.menu.view.zoomOut": "缩小",
    "titleBar.menu.window.minimize": "最小化",
    "titleBar.menu.window.zoom": "缩放",
    "titleBar.menu.window.bringAllToFront": "全部置于前台",
    "titleBar.menu.app.services": "服务",
    "titleBar.menu.app.hide": "隐藏 {appName}",
    "titleBar.menu.app.hideOthers": "隐藏其他",
    "titleBar.menu.app.showAll": "全部显示",
    "titleBar.menu.app.quit": "退出 {appName}",
    "titleBar.menu.help.about": "关于 yazcode",
    "titleBar.menu.help.whatsNew": "更新日志",
    "titleBar.menu.help.checkForUpdates": "检查更新",
    "titleBar.menu.help.toggleDevTools": "切换开发者工具",
    "titleBar.menu.help.resourceManager": "资源管理器",
    "titleBar.menu.help.toggleZCodeStdioTap": "抓取 Agent stdio 通信",
    "titleBar.menu.help.zcodeEndpoint": "ZCode Endpoint",
    "titleBar.menu.help.zcodeEndpoint.production": "Production（默认）",
    "titleBar.menu.help.zcodeEndpoint.test": "Test",
    "titleBar.menu.help.zcodeEndpoint.custom": "自定义...",
    "titleBar.menu.help.zcodeEndpoint.reset": "恢复默认",
    "titleBar.menu.help.feedback": "问题上报",
    "titleBar.menu.help.exportLogs": "导出日志",
    "titleBar.menu.help.clearAllData": "清除所有数据",
    "desktopMenu.help.checkingForUpdates": "正在检查更新...",
    "desktopMenu.help.updateAvailableVersion": "发现新版本 {version}",
    "desktopMenu.help.downloadingUpdateVersion": "正在下载更新 {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "正在下载更新... {progress}",
    "desktopMenu.help.restartToUpdate": "重启以更新（{version}）",
    "dock.menu.showCurrentWindow": "显示当前窗口",
    "tray.tooltip": "yazcode",
    "tray.menu.openZCode": "打开 yazcode",
    "tray.menu.quit": "退出",
  },
  "en-US": {
    "titleBar.menu.file": "File",
    "titleBar.menu.edit": "Edit",
    "titleBar.menu.view": "View",
    "titleBar.menu.window": "Window",
    "titleBar.menu.help": "Help",
    "titleBar.menu.file.newTask": "New task",
    "titleBar.menu.file.openWorkspace": "Open workspace",
    "titleBar.menu.file.closeWindow": "Close window",
    "titleBar.menu.edit.undo": "Undo",
    "titleBar.menu.edit.redo": "Redo",
    "titleBar.menu.edit.cut": "Cut",
    "titleBar.menu.edit.copy": "Copy",
    "titleBar.menu.edit.paste": "Paste",
    "titleBar.menu.edit.delete": "Delete",
    "titleBar.menu.edit.selectAll": "Select all",
    "titleBar.menu.view.toggleFullScreen": "Toggle full screen",
    "titleBar.menu.view.actualSize": "Actual size",
    "titleBar.menu.view.zoomIn": "Zoom in",
    "titleBar.menu.view.zoomOut": "Zoom out",
    "titleBar.menu.window.minimize": "Minimize",
    "titleBar.menu.window.zoom": "Zoom",
    "titleBar.menu.window.bringAllToFront": "Bring all to front",
    "titleBar.menu.app.services": "Services",
    "titleBar.menu.app.hide": "Hide {appName}",
    "titleBar.menu.app.hideOthers": "Hide others",
    "titleBar.menu.app.showAll": "Show all",
    "titleBar.menu.app.quit": "Quit {appName}",
    "titleBar.menu.help.about": "About yazcode",
    "titleBar.menu.help.whatsNew": "What's new",
    "titleBar.menu.help.checkForUpdates": "Check for updates",
    "titleBar.menu.help.toggleDevTools": "Toggle developer tools",
    "titleBar.menu.help.resourceManager": "Resource manager",
    "titleBar.menu.help.toggleZCodeStdioTap": "Capture agent stdio traffic",
    "titleBar.menu.help.zcodeEndpoint": "ZCode Endpoint",
    "titleBar.menu.help.zcodeEndpoint.production": "Production (default)",
    "titleBar.menu.help.zcodeEndpoint.test": "Test",
    "titleBar.menu.help.zcodeEndpoint.custom": "Custom...",
    "titleBar.menu.help.zcodeEndpoint.reset": "Reset to default",
    "titleBar.menu.help.feedback": "Feedback",
    "titleBar.menu.help.exportLogs": "Export logs",
    "titleBar.menu.help.clearAllData": "Clear all data",
    "desktopMenu.help.checkingForUpdates": "Checking for updates...",
    "desktopMenu.help.updateAvailableVersion": "Update available {version}",
    "desktopMenu.help.downloadingUpdateVersion": "Downloading update {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "Downloading update... {progress}",
    "desktopMenu.help.restartToUpdate": "Restart to update ({version})",
    "dock.menu.showCurrentWindow": "Show current window",
    "tray.tooltip": "yazcode",
    "tray.menu.openZCode": "Open yazcode",
    "tray.menu.quit": "Quit",
  },
  "fa-IR": {
    "titleBar.menu.file": "فایل",
    "titleBar.menu.edit": "ویرایش",
    "titleBar.menu.view": "نمایش",
    "titleBar.menu.window": "پنجره",
    "titleBar.menu.help": "راهنما",
    "titleBar.menu.file.newTask": "وظیفه جدید",
    "titleBar.menu.file.openWorkspace": "باز کردن فضای کاری",
    "titleBar.menu.file.closeWindow": "بستن پنجره",
    "titleBar.menu.edit.undo": "واگرد",
    "titleBar.menu.edit.redo": "ازنو",
    "titleBar.menu.edit.cut": "برش",
    "titleBar.menu.edit.copy": "کپی",
    "titleBar.menu.edit.paste": "چسباندن",
    "titleBar.menu.edit.delete": "حذف",
    "titleBar.menu.edit.selectAll": "انتخاب همه",
    "titleBar.menu.view.toggleFullScreen": "تغییر حالت تمام‌صفحه",
    "titleBar.menu.view.actualSize": "اندازه واقعی",
    "titleBar.menu.view.zoomIn": "بزرگ‌نمایی",
    "titleBar.menu.view.zoomOut": "کوچک‌نمایی",
    "titleBar.menu.window.minimize": "کوچک کردن",
    "titleBar.menu.window.zoom": "زوم",
    "titleBar.menu.window.bringAllToFront": "آوردن همه به جلو",
    "titleBar.menu.app.services": "خدمات",
    "titleBar.menu.app.hide": "پنهان کردن {appName}",
    "titleBar.menu.app.hideOthers": "پنهان کردن بقیه",
    "titleBar.menu.app.showAll": "نمایش همه",
    "titleBar.menu.app.quit": "خروج از {appName}",
    "titleBar.menu.help.about": "درباره yazcode",
    "titleBar.menu.help.whatsNew": "تازه‌ها",
    "titleBar.menu.help.checkForUpdates": "بررسی به‌روزرسانی‌ها",
    "titleBar.menu.help.toggleDevTools": "نمایش/پنهان‌سازی ابزارهای توسعه‌دهنده",
    "titleBar.menu.help.resourceManager": "مدیر منابع",
    "titleBar.menu.help.toggleZCodeStdioTap": "ضبط ترافیک stdio ایجنت",
    "titleBar.menu.help.zcodeEndpoint": "ZCode Endpoint",
    "titleBar.menu.help.zcodeEndpoint.production": "Production (پیش‌فرض)",
    "titleBar.menu.help.zcodeEndpoint.test": "Test",
    "titleBar.menu.help.zcodeEndpoint.custom": "سفارشی...",
    "titleBar.menu.help.zcodeEndpoint.reset": "بازگردانی به پیش‌فرض",
    "titleBar.menu.help.feedback": "بازخورد",
    "titleBar.menu.help.exportLogs": "برون‌برد گزارش‌ها",
    "titleBar.menu.help.clearAllData": "پاک کردن همه داده‌ها",
    "desktopMenu.help.checkingForUpdates": "در حال بررسی به‌روزرسانی...",
    "desktopMenu.help.updateAvailableVersion": "نسخه {version} موجود است",
    "desktopMenu.help.downloadingUpdateVersion": "در حال دانلود به‌روزرسانی {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "در حال دانلود به‌روزرسانی... {progress}",
    "desktopMenu.help.restartToUpdate": "برای به‌روزرسانی، دوباره راه‌اندازی کنید ({version})",
    "dock.menu.showCurrentWindow": "نمایش پنجره فعلی",
    "tray.tooltip": "yazcode",
    "tray.menu.openZCode": "باز کردن yazcode",
    "tray.menu.quit": "خروج",
  },
};

export function getDesktopMenuMessage(locale: Locale, id: DesktopMenuMessageId): string {
  const messages = desktopMenuMessages[locale] ?? desktopMenuMessages[DEFAULT_LOCALE];
  return messages[id];
}

export function formatDesktopMenuMessage(
  locale: Locale,
  id: DesktopMenuMessageId,
  values?: Record<string, string | number>,
): string {
  let message = getDesktopMenuMessage(locale, id);
  if (!values) {
    return message;
  }

  for (const [key, value] of Object.entries(values)) {
    message = message.replaceAll(`{${key}}`, String(value));
  }

  return message;
}
